apiVersion: v1
kind: Service
metadata:
  name: web-deploy-svc
spec:
  type: ClusterIP
  selector:
    app: web-deploy            # matches the Deployment's Pod labels, NOT the Deployment itself
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
