apiVersion: v1
kind: ConfigMap
metadata:
  name: python-api-config
  labels:
    app: python-api
data:
  DB_HOST: "postgres-db"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_SSLMODE: "disable"
  DB_CONNECT_TIMEOUT: "5"
