apiVersion: v1
kind: Service
metadata:
  name: node-api
  labels:
    app: node-apo
spec:
  type: ClusterIP
  selector:
    app: node-apo
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
